### ISSUE TITLE
TLS Support

### ISSUE THREAD

**Issue by eldridge** [processone/p1_mysql#7]
I'm migrating [this ticket](https://github.com/processone/mysql/issues/6) from the processone/mysql repository so that it doesn't get lost.

Modern best practices and associated regulation calls for database connections to be encrypted, which is of paramount importance when used with contemporary multi-tenant cloud platforms wherein data may be transiting network nodes shared among multiple customers.

GDPR includes strong support for encryption and the forthcoming TLS 1.3 protocol mandates the use of ephemeral keys for supporting perfect forward secrecy.

I would love to provide the implementation, but as I understand it, this is a pure-erlang driver, and I know next to nothing about Erlang.  It is unfortunate that the baby is being thrown out with the bath water, so to speak, when features supported by reference libraries are not implemented alongside these types of re-implementations.

**Comment by zinid** [comment]
1) We clearly understand importance of TLS in some usages
2) I already tried to bring TLS to the driver. I actually did it already for PostgreSQL driver, but MySQL's STARTTLS implementation is retarded and requires quite invasive library update, so even with Erlang skills the task is not easy.

I will keep this ticket as a reminder though.

**Comment by prefiks** [comment]
This was fixed in a34873415d3e66de98f5abfe89406fade9915964
