### ISSUE TITLE
Just little curious 

### ISSUE THREAD

**Issue by grizzly-monkey** [processone/p1_mysql#8]
Why was p1_mysql written as pure erlang implementation and not used libmysql  as nif or port binding which could under the hood do SSL/ stored proc calls etc...  and all the upstream changes ready made in the c implementation.

**Comment by zinid** [comment]
> Why was p1_mysql written as pure erlang implementation

For historical reasons, also note that the driver itself is not written by P1, it was just adopted later.

**Comment by grizzly-monkey** [comment]
okay i was trying to write implemenation for mongodb driver for ejabberd but not using existing lib that is there they are pure erlang libs the problem is with the performance support and the number of options that existing lib provides are very less so was thinking if i could write a port / nif for the same and integrate with with ejabberd .

the issue i am having is if i should go with NIF approach or port apporach.

if you were to write mysql binding what would you choose nif or port ? would that be multi threaded or single threaded ?
Any aspects that i should consider as part of design ?

**Comment by zinid** [comment]
> if you were to write mysql binding what would you choose nif or port ? would that be multi threaded or single threaded?

Hard to say, I need to play with different approaches to find the right way, due to specifics of the task. I would go multi-threaded NIF almost certainly (despite the driver API has nice built-in thread pool, see `driver_async()` function). The question is mostly whether I would use dirty schedulers or hand written thread pool. I really cannot say, but from top of my head I would go with the latter *IF* the C library in question doesn't support connection pool by itself.

**Comment by grizzly-monkey** [comment]
Thanks for your view on this @zinid  driver does support connection pooling being this the case i would try to experiment with  dirty schedulers + NIF let see how it goes  thanks for your time :)

**Comment by zinid** [comment]
You're welcome.
For the record, it's better to ask such questions in ejabberd conference: ejabberd@conference.process-one.net. Use any XMPP client with MUC support to join.

**Comment by grizzly-monkey** [comment]
@zinid  I tried to connect to jabber server ejabberd@conference.process-one.net.  but looks like registrations are not open i am not able to register on it.
So i am writing here.
as per this issue I tried to write multi-tenant mongo client for erlang. 
https://github.com/grizzly-monkey/emongo

I would be really thankful if you can just take a look at it and see if my approach to write this was correct and can suggest your point of you .
I have started integrating this to ejabberd so that other people can benefit from the same.
if there is any other medium of communication that i could use to connect with you on this will be great.

**Comment by zinid** [comment]
> I tried to connect to jabber server ejabberd@conference.process-one.net. but looks like registrations are not open i am not able to register on it.

What do you mean? There are no registration in this conference. You can join it from any XMPP account.

**Comment by zinid** [comment]
BTW, I don't know C++ (I know C only) so I cannot verify the code.
